
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiroaccount?serverTimezone=GMT
    username: root
    password: herui15823439009
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true